language : C++
# compiler : clang
os:
  - linux
  - osx
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#ublab
    template:
    - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
  

script : g++ -o main code.cc

  
  
